package com.segeon.chinchilla.server.dal.model;

import java.util.Date;

public class ApplicationProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_profile.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_profile.application_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_profile.profile_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_profile.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_profile.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_profile.id
     *
     * @return the value of application_profile.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_profile.id
     *
     * @param id the value for application_profile.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_profile.application_id
     *
     * @return the value of application_profile.application_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_profile.application_id
     *
     * @param applicationId the value for application_profile.application_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_profile.profile_id
     *
     * @return the value of application_profile.profile_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_profile.profile_id
     *
     * @param profileId the value for application_profile.profile_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_profile.add_time
     *
     * @return the value of application_profile.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_profile.add_time
     *
     * @param addTime the value for application_profile.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_profile.update_time
     *
     * @return the value of application_profile.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_profile.update_time
     *
     * @param updateTime the value for application_profile.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}