package com.segeon.chinchilla.server.dal.model;

import java.util.Date;

public class ConfModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_module.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_module.conf_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer confId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_module.module_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_module.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_module.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_module.id
     *
     * @return the value of conf_module.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_module.id
     *
     * @param id the value for conf_module.id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_module.conf_id
     *
     * @return the value of conf_module.conf_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_module.conf_id
     *
     * @param confId the value for conf_module.conf_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_module.module_id
     *
     * @return the value of conf_module.module_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_module.module_id
     *
     * @param moduleId the value for conf_module.module_id
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_module.add_time
     *
     * @return the value of conf_module.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_module.add_time
     *
     * @param addTime the value for conf_module.add_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_module.update_time
     *
     * @return the value of conf_module.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_module.update_time
     *
     * @param updateTime the value for conf_module.update_time
     *
     * @mbggenerated Tue Oct 04 20:02:46 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}