package com.segeon.chinchilla.server.dal.model;

import java.util.Date;

public class ConfVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.profile_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.current_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer currentVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.top_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer topVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_version.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.id
     *
     * @return the value of conf_version.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.id
     *
     * @param id the value for conf_version.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.application_id
     *
     * @return the value of conf_version.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.application_id
     *
     * @param applicationId the value for conf_version.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.profile_id
     *
     * @return the value of conf_version.profile_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.profile_id
     *
     * @param profileId the value for conf_version.profile_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.current_version
     *
     * @return the value of conf_version.current_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getCurrentVersion() {
        return currentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.current_version
     *
     * @param currentVersion the value for conf_version.current_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setCurrentVersion(Integer currentVersion) {
        this.currentVersion = currentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.top_version
     *
     * @return the value of conf_version.top_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getTopVersion() {
        return topVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.top_version
     *
     * @param topVersion the value for conf_version.top_version
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setTopVersion(Integer topVersion) {
        this.topVersion = topVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.add_time
     *
     * @return the value of conf_version.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.add_time
     *
     * @param addTime the value for conf_version.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_version.update_time
     *
     * @return the value of conf_version.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_version.update_time
     *
     * @param updateTime the value for conf_version.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}