package com.segeon.chinchilla.server.dal.model;

import java.util.Date;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.name
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.code
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.description
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.application_id
     *
     * @return the value of module.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.application_id
     *
     * @param applicationId the value for module.application_id
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.name
     *
     * @return the value of module.name
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.name
     *
     * @param name the value for module.name
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.code
     *
     * @return the value of module.code
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.code
     *
     * @param code the value for module.code
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.description
     *
     * @return the value of module.description
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.description
     *
     * @param description the value for module.description
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.add_time
     *
     * @return the value of module.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.add_time
     *
     * @param addTime the value for module.add_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.update_time
     *
     * @return the value of module.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.update_time
     *
     * @param updateTime the value for module.update_time
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}