package com.segeon.chinchilla.server.dal.mapper;

import com.segeon.chinchilla.server.dal.model.ApplicationProfile;
import com.segeon.chinchilla.server.dal.model.ApplicationProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int countByExample(ApplicationProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int deleteByExample(ApplicationProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int insert(ApplicationProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int insertSelective(ApplicationProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    List<ApplicationProfile> selectByExample(ApplicationProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    ApplicationProfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ApplicationProfile record, @Param("example") ApplicationProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int updateByExample(@Param("record") ApplicationProfile record, @Param("example") ApplicationProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int updateByPrimaryKeySelective(ApplicationProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_profile
     *
     * @mbggenerated Wed Jun 29 23:12:06 CST 2016
     */
    int updateByPrimaryKey(ApplicationProfile record);
}