package com.segeon.chinchilla.server.dal.mapper;

import com.segeon.chinchilla.server.dal.model.ConfModule;
import com.segeon.chinchilla.server.dal.model.ConfModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int countByExample(ConfModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int deleteByExample(ConfModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int insert(ConfModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int insertSelective(ConfModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    List<ConfModule> selectByExample(ConfModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    ConfModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") ConfModule record, @Param("example") ConfModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByExample(@Param("record") ConfModule record, @Param("example") ConfModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByPrimaryKeySelective(ConfModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf_module
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByPrimaryKey(ConfModule record);
}