package com.segeon.chinchilla.server.dal.mapper;

import com.segeon.chinchilla.server.dal.model.Conf;
import com.segeon.chinchilla.server.dal.model.ConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int countByExample(ConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int deleteByExample(ConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int insert(Conf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int insertSelective(Conf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    List<Conf> selectByExample(ConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    Conf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") Conf record, @Param("example") ConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByExample(@Param("record") Conf record, @Param("example") ConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByPrimaryKeySelective(Conf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conf
     *
     * @mbggenerated Sat Jun 18 22:02:40 CST 2016
     */
    int updateByPrimaryKey(Conf record);
}